### ISSUE TITLE
css: tag page TD width is burst

### ISSUE THREAD

**Issue by yurenchen000** [Quiq/docker-registry-ui#70]
the field of `moby.buildkit.buildinfo.v1` in Image History 
has a long (but without space) line base64, which burst the cell width.

os: ubuntu
browser: chrome 113, firefox 113

![docker_reg_ui-](https://github.com/Quiq/docker-registry-ui/assets/8458213/6233f081-b19d-4caf-89de-a859b62791dd)

**Comment by yurenchen000** [comment]
a css patch to fix it:

```css
/* td: long line wrap */
td {
    word-break: break-word;
}
```

**Comment by yurenchen000** [comment]
other css made table more readable (maybe)
```css
/* col 0 style */
td:nth-child(1) {
    color: #838383;
    text-align: right;
}
```

//after
![docker_ui_after-](https://github.com/Quiq/docker-registry-ui/assets/8458213/add5ffe5-27d8-49b7-be27-92203f328c70)

//before
![docker_ui_before-](https://github.com/Quiq/docker-registry-ui/assets/8458213/31613558-66be-483a-874b-d738650503b7)
